[build]
  command = "npm install && npm run build"
  publish = "dist/public"

[dev]
  command = "npm run dev"
  targetPort = 3000
  publish = "dist/public"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@neondatabase/serverless"]
